### ISSUE TITLE
AttributeError: StanfordCoreNLP instance has no attribute 'annotate'

### ISSUE THREAD

**Issue by pathaine** [xmb-cipher/fofe-ner#3]
Hello,

Thank you so much for putting your code online!
When I run kbp-xml-parser.py, I get the following error: AttributeError: StanfordCoreNLP instance has no attribute 'annotate'
I'm connecting to the StanfordCoreNLP server just fine. '.parse(...)' works just fine. 

Many thanks!
Patricia

**Comment by xmb-cipher** [comment]
@pathaine Thanks for your interest. You have to launch CoreNLP server on the background. We make use of CoreNLP to perform "ssplit" and "tokenize". https://stanfordnlp.github.io/CoreNLP/corenlp-server.html

**Comment by pathaine** [comment]
Thank you for your quick response!
I had launched the server. When I don't, I get a: Exception AttributeError: "StanfordCoreNLP instance has no attribute 'corenlp'" error.
For the .annotate error I get the "AttributeError: StanfordCoreNLP instance has no attribute 'annotate'" message.
Maybe there was a StanfordCoreNLP version change? I'm running 3.7.0

Thanks again!

**Comment by xmb-cipher** [comment]
@pathaine May I have your error stack? 
I installed a python wrapper called pycorenlp. Maybe this package is updated?  
The underlying implantation of this package sends http requests to CoreNLP server.

**Comment by pathaine** [comment]
**When I start the server on I get:**

~/.local/lib/python2.7/site-packages/pycorenlp$ java -mx4g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer -port 9000 -timeout 15000
[main] INFO CoreNLP - --- StanfordCoreNLPServer#main() called ---
[main] INFO CoreNLP - setting default constituency parser
[main] INFO CoreNLP - warning: cannot find edu/stanford/nlp/models/srparser/englishSR.ser.gz
[main] INFO CoreNLP - using: edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz instead
[main] INFO CoreNLP - to use shift reduce parser download English models jar from:
[main] INFO CoreNLP - http://stanfordnlp.github.io/CoreNLP/download.html
[main] INFO CoreNLP -     Threads: 32
[main] INFO CoreNLP - Starting server...
[main] INFO CoreNLP - StanfordCoreNLPServer listening at /0:0:0:0:0:0:0:0:9000

**Unfortunately, the error stack is not very informative:**

$ python kbp-xml-parser.py documents/ parsed/
2017-05-02 07:27:11,640 : INFO : Namespace(input_dir='documents/', language='eng', mention=None, output_dir='parsed/', quote=None, sentence_only=False, url='http://localhost:9000', verbose=False)
('corenlp_path: ', '/u/pthaine/.local/lib/python2.7/site-packages/pycorenlp/')
2017-05-02 07:27:19,448 : ERROR : test.ldc
Traceback (most recent call last):
  File "kbp-xml-parser.py", line 151, in process_one_file
    parsed = nlp.annotate(  text, properties = properties )
AttributeError: StanfordCoreNLP instance has no attribute 'annotate'
2017-05-02 07:27:19,449 : ERROR : Test
Traceback (most recent call last):
  File "kbp-xml-parser.py", line 151, in process_one_file
    parsed = nlp.annotate(  text, properties = properties )
AttributeError: StanfordCoreNLP instance has no attribute 'annotate'
2017-05-02 07:27:19,462 : ERROR : test.ldc
Traceback (most recent call last):
  File "kbp-xml-parser.py", line 151, in process_one_file
    parsed = nlp.annotate(  text, properties = properties )
AttributeError: StanfordCoreNLP instance has no attribute 'annotate'
2017-05-02 07:27:19,462 : ERROR : This is a test.
Traceback (most recent call last):
  File "kbp-xml-parser.py", line 151, in process_one_file
    parsed = nlp.annotate(  text, properties = properties )
AttributeError: StanfordCoreNLP instance has no attribute 'annotate'
2017-05-02 07:27:19,464 : INFO : test.ldc processed

2017-05-02 07:27:19,464 : INFO : fail to parse: 0

**test.ldc contains the following:**

```
<doc id="test_01">
<headline>
Test
</headline>
<post author="Pat" datetime="2017-05-01T12:00:00" id="t1">
This is a test.
</post>
</doc>

```
Again, thank you very much!

**Comment by xmb-cipher** [comment]
@pathaine Are you using this wrapper https://github.com/smilli/py-corenlp? This repository is frozen for a very long time.

**Comment by pathaine** [comment]
That's the wrapper I am using :)
I figured out the issue -- in kbd-xml-parser.py, the text being input into 'annotate' is in unicode and corenlp wants it to be ascii. It works now! Thank you so much for your time!
