### ISSUE TITLE
FOFE-NER for Chinese

### ISSUE THREAD

**Issue by bunnyfighting** [xmb-cipher/fofe-ner#4]
Hello,
     Thank you for uploading your code. Your idea is very interesting. But I have some questions for your Chinese model. 
    
     1.What is the model level for Chinese? Character level ?

     2.When you deal with Chinese, you don't use FOFE encoding? In 'gigaword2feature.pyx',  the function  'char_fofe_of_word' and' char_fofe_of_phrase'  of  'class chinese_word_vocab' don't have implement. But these functions will be used in 'class batch_constructor'.

     3.Could you give me a data sample of KBP for Chinese?
     Thank you so much!

**Comment by xmb-cipher** [comment]
@bunnyfighting 
Thanks for your interest.

1. Yes, Chinese is modelled at character level.

2. It's instantiated here https://github.com/xmb-cipher/fofe-ner/blob/master/kbp-ed-trainer.py#L130. Thanks to polymorphism, the version from the class "vocabulary" is actually invoked. Sorry that it's not nice written. 

3. before kbp-xml-parser
[before.txt](https://github.com/xmb-cipher/fofe-ner/files/981335/before.txt)
and after
[after.txt](https://github.com/xmb-cipher/fofe-ner/files/981336/after.txt)

**Comment by bunnyfighting** [comment]
Thanks a lot for your prompt reply.

1. It's very beneficial for me to understand why the char sequence is equal to the word sequence.(https://github.com/xmb-cipher/fofe-ner/blob/master/source/gigaword2feature.pyx#L858)

2. The variable name 'has_char_feature' makes me confused which features should be used to create the Chinese model. Modifying the variable name may be better. (https://github.com/xmb-cipher/fofe-ner/blob/master/source/gigaword2feature.pyx#L967) 

Your code makes me understand your model better. Thank you very much for your help!

**Comment by xmb-cipher** [comment]
@bunnyfighting 
1. case-sensitive embedding == character embedding, case-insensitive embedding == source word's embedding.
For example, ”学“ in the sentence "我 是 学生“ will use the embedding of character "学" and word embedding of "学生".

2. Chinese article may contain non-Chinese character, say English words. I don't treat the them as a character sequence but a single "character". 
For example, “nice” in "今天的天气很nice” is viewed a "Chinese character".

**Comment by xmb-cipher** [comment]
@bunnyfighting 
Sorry, I had  careful look today and found that I gave you a wrong answer.

char_fofe_of_word and char_fofe_of_phrase are not implemented because 
1. the basic units are characters, which play the role of word in other language.
2. character is indecomposable.

**Comment by bunnyfighting** [comment]
Thank you for your detailed explanation.

1. The charcter is indecomposable for Chinese. But you use the word embedding or the char embedding to replace the one-hot vector of the t-th word or char in the sentence. So Chinese can use the FOEF. I think if Chinese has fewer characters, it may use the same way to construct the FOEF like English. 

2. The words sequence of a sentence will have repeated words. Your Chinese model uses the words sequence as the input. But these repeated words may have a bad effect? These sequences aren't consistent with human intuition.
     For example,  the sentence "我是学生“ can generate a words sequence "我 / 是 / 学生 / 学生"

**Comment by xmb-cipher** [comment]
@bunnyfighting It's constructed in the same way. Since it's linear, we could place the recursion after embedding lookup. They're mathematically equivalent (http://www.aclweb.org/anthology/P15-2081). I implemented it using sparse matrix because I have other ideas to try and it's more suitable for those ideas.
